# ===== RENDER.YAML =====
services:
  - type: web
    name: real-estate-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python -m app.scripts.seed_data && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://real-estate-frontend.onrender.com
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

  - type: web
    name: real-estate-frontend
    env: static
    region: oregon
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://real-estate-backend.onrender.com

databases:
  - name: real-estate-db
    databaseName: realestate
    user: realestate_user
    region: oregon
    plan: starter
